Spring:
  h2:
    console:
      enabled: true
    path: /h2-console
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  datasource:
    url: jdbc:h2:tcp://localhost/~/sbb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace